#!/bin/sh
set -eu
ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
VERSION=$(/usr/libexec/PlistBuddy -c 'Print :CFBundleShortVersionString' "$ROOT/Resources/Info.plist")
APP=${1:-"$ROOT/build/releases/TheClipboard/$VERSION/The Clipboard.app"}
# Core/platform test libraries are generated by test-representations.sh.
"$ROOT/Scripts/test-representations.sh"
swiftc -I "$ROOT/build/tests" -L "$ROOT/build/tests" -lClipboardCore \
  -Xlinker -rpath -Xlinker "$ROOT/build/tests" \
  "$ROOT/Sources/TheClipboard/ApplicationIdentity.swift" "$ROOT/Sources/TheClipboard/AboutInformation.swift" \
  "$ROOT/Sources/TheClipboard/ApplicationIconController.swift" \
  "$ROOT/Tests/IdentityChecks.swift" -o "$ROOT/build/tests/identity-checks"
"$ROOT/build/tests/identity-checks" "$APP"
